Fixing pipeline

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -29,11 +29,6 @@ jobs:
           POSTGRES_PASSWORD: admin12345
         ports:
           - 5432:5432
-        options: >-
-          --health-cmd="pg_isready -U postgres -d postgres"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
 
     steps:
       - name: Checkout repository
@@ -42,10 +37,17 @@ jobs:
       - name: Wait for PostgreSQL to be healthy
         run: |
           echo "Waiting for PostgreSQL to be healthy..."
-          until [ "`docker inspect -f {{.State.Health.Status}} postgres`" == "healthy" ]; do
-            sleep 5;
+          for i in {1..10}; do
+            pg_isready -h localhost -p 5432 -U postgres
+            if [ $? -eq 0 ]; then
+              echo "PostgreSQL is healthy."
+              exit 0
+            fi
+            echo "PostgreSQL is not healthy yet. Retrying in 5 seconds..."
+            sleep 5
           done
-          echo "PostgreSQL is healthy."
+          echo "Failed to connect to PostgreSQL."
+          exit 1
 
       - name: Verify database connection
         run: |
