Update docker-publish.yml, added jobs

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -16,53 +16,28 @@ jobs:
       - name: List files in the repository
         run: ls -al
 
-  check-db-connection:
+  check-required-files:
     runs-on: ubuntu-latest
     needs: list-files
-
-    services:
-      postgres:
-        image: postgres:13
-        env:
-          POSTGRES_DB: postgres
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: admin12345
-        ports:
-          - 5432:5432
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Wait for PostgreSQL to be healthy
+      - name: Check for required files
         run: |
-          echo "Waiting for PostgreSQL to be healthy..."
-          for i in {1..10}; do
-            pg_isready -h localhost -p 5432 -U postgres
-            if [ $? -eq 0 ]; then
-              echo "PostgreSQL is healthy."
-              exit 0
+          required_files=("Dockerfile" "docker-compose.yaml" "entrypoint.sh" "requirements.txt" "settings.py" ".env")
+          for file in "${required_files[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "Error: $file is missing!"
+              exit 1
             fi
-            echo "PostgreSQL is not healthy yet. Retrying in 5 seconds..."
-            sleep 5
           done
-          echo "Failed to connect to PostgreSQL."
-          exit 1
-
-      - name: Verify database connection
-        run: |
-          echo "Checking database connection..."
-          PGPASSWORD=admin12345 pg_isready -h localhost -p 5432 -U postgres -d postgres
-          if [ $? -eq 0 ]; then
-            echo "Database connection is OK."
-          else
-            echo "Failed to connect to database."
-            exit 1
-          fi
+          echo "All required files are present."
 
   build-and-push:
     runs-on: ubuntu-latest
-    needs: [list-files, check-db-connection]
+    needs: [list-files, check-required-files]
 
     steps:
       - name: Checkout repository
